#!/bin/sh
# zdmenu_path - cache and list executables for zdmenu

cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
cache="$cachedir/zdmenu_run"

[ -d "$cachedir" ] || mkdir -p "$cachedir"

IFS=:
if stest -dqr -n "$cache" $PATH; then
    stest -flx $PATH | sort -u | tee "$cache"
else
    cat "$cache"
fi